---
project_name: tnscli
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm
      - linux_arm64
      - darwin_amd64
      - windows_amd64
    ldflags:
      - -s -w
      - -X {{ .ProjectName }}/cmd.Version={{.Version}}
      - -X {{ .ProjectName }}/cmd.Commit={{.ShortCommit}}
      - -X {{ .ProjectName }}/cmd.Date={{time "2006-01-02"}}
      - -X {{ .ProjectName }}/cmd.Name={{.ProjectName}}

changelog:
  use: git
  filters:
    exclude:
      - '^Merge branch'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-beta"

archives:
  - id: archive
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    strip_binary_directory: true
    files:
      - "*.md"
      - LICENSE
      - scripts/*

nfpms:
  - id: packages
    # dont use {{ .ProjectName }} here :(
    package_name: tnscli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # builds:
    maintainer: "Tommi2Day <tommi2day@github.com>"
    description: |-
      Small Oracle TNS Service and Connect Test Tool
    formats:
      - rpm
      - deb
    # dependencies:
    provides:
      # dont use {{ .ProjectName }} here :(
      - tnscli
    contents:
      - src: "*.md"
        dst: /usr/share/doc/{{ .ProjectName }}/
      - src: LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/
      - src: scripts/*
        dst: /usr/bin


release:
  github:
    owner: tommi2day
    name: tnscli
  replace_existing_draft: true
  draft: true
  header: |
    ## TNSCLI Release {{ .Tag }} ({{ time "2006-01-02" }})
  target_commitish: '{{ .Commit }}'
