---
project_name: tnscli

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
    targets:
      - linux_amd64
      - linux_arm
      - darwin_amd64
      - windows_amd64
    ldflags:
      - -s -w
      - -X {{ .ProjectName }}/cmd.Version={{.Version}}
      - -X {{ .ProjectName }}/cmd/.Commit={{.ShortCommit}}
      - -X {{ .ProjectName }}/cmd.Date={{time "2006-01-02"}}
      - -X {{ .ProjectName }}/cmd.Name={{.ProjectName}}

changelog:
  use: git
  filters:
    exclude:
      - '^Merge branch'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Refactoring'
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

archives:
  - id: archive
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: deb-packages
    # dont use {{ .ProjectName }} here :(
    package_name: tnscli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # builds:
    license: GPL-3
    bindir: /usr/bin
    vendor: Tommi2Day
    maintainer: "Tommi2Day <tommi2day@github.com>"
    description: |-
      Small Oracle TNS Service and Connect Test Tool
    formats:
      - deb
    # dependencies:
    provides:
      # dont use {{ .ProjectName }} here :(
      - tnscli
    contents:
      - src: scripts/*
        dst: /usr/local/bin

  - id: rpm-packages
    # dont use {{ .ProjectName }} here :(
    package_name: tnscli
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # builds:
    maintainer: "Tommi2Day <tommi2day@github.com>"
    description: |-
      Small Oracle TNS Service and Connect Test Tool
    formats:
      - rpm
    # dependencies:
    provides:
      # dont use {{ .ProjectName }} here :(
      - tnscli
    contents:
      - src: scripts/*
        dst: /usr/local/bin

release:
  github:
    owner: tommi2day
    name: tnscli
  replace_existing_draft: true
  draft: true
  header: |
    ## TNSCLI Release {{ .Tag }} ({{ time "2006-01-02" }})
  target_commitish: '{{ .Commit }}'
