name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Install dependencies
        run: |
          go mod tidy
          go mod vendor
      - name: Test
        env:
          # GitHub copies the files with api, not as clone, check fails
          # https://github.com/actions/checkout/issues/335
          SKIP_COMMIT: true
          # github cannot handle custom resolvers, so skip dns tests
          SKIP_DNS: true
        run: go test -v ./...  -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false
      - uses: golangci/golangci-lint-action@v9
        with:
          args: --verbose --timeout=10m --config=.golangci.yml ./...
          only-new-issues: false
          skip-cache: true